[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # These vars tell Netlify's secrets scanner to skip known safe client keys
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "true"
